matrix:
    include:
      - language: java
        before_install:
          - wget https://dl.bintray.com/spdx/spdx-tools/org/spdx/spdx-tools/2.1.8/spdx-tools-2.1.8-jar-with-dependencies.jar
        script: 
          - 'if [[ "$TRAVIS_PULL_REQUEST" = "false" && "master" = "$TRAVIS_BRANCH" ]]; then ./.travis/testPublishLicenseList.sh; else ./.travis/testBuildLicenseList.sh; fi'
      - language: node_js
        node_js:
          - "node"
