#!/bin/bash

TOOL_VERSION=`awk '/^TOOL_VERSION/{print $NF}' Makefile`
PUBLISHER=licenseListPublisher-${TOOL_VERSION}.jar

# if license list publisher is not present, download it
test ! -f ${PUBLISHER}  && make ${PUBLISHER}-valid

for test_file in \
        "test/simpleTestForGenerator/$1.txt" \
        test/simpleTestForGenerator/$1.*.txt; do
        if [ -f "$test_file" ]; then
                echo "Testing $test_file"
                java -jar ${PUBLISHER} TestLicenseXML "src/$1.xml" "$test_file"
        fi
done
