#!/usr/bin/env bash
#
# Usage:
# ./test-one-license <Short ID>
#
# any other command line arguments are ignored

TOOL_VERSION="$(awk '/^TOOL_VERSION/{print $NF}' Makefile)"
PUBLISHER=licenseListPublisher-${TOOL_VERSION}.jar

# if license list publisher is not present, download it
test ! -f "${PUBLISHER}" && make "${PUBLISHER}-valid"

java -jar "${PUBLISHER}" TestLicenseXML "src/${1}.xml" "test/simpleTestForGenerator/${1}.txt" "test/fullTestForGenerator"
